behaviors:
  VikramRover:
    trainer_type: sac
    hyperparameters:
      batch_size: 128
      buffer_size: 1200
      learning_rate: 3.0e-4
      # beta: 5.0e-4
      # epsilon: 0.2
      # lambd: 0.95
      # num_epoch: 3
      learning_rate_schedule: linear
      # beta_schedule: constant
      # epsilon_schedule: linear
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 10.0
      save_replay_buffer: false
      init_entcoef: 0.5
      reward_signal_steps_per_update: 10.0
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    checkpoint_interval: 100000
    max_steps: 500000
    time_horizon: 64
    summary_freq: 10000
    